In [4]:
import numpy as np

#a)
m_transposta = np.array([[1.000000,0.748264,0.748264,0.101266], [1.000000,0.814647,0.271173,0.331211], [1.000000,0.71770,0.096328,0.711770], [1.000000,0.882497,0.161218,0.653770]])
m_normal = np.array([[1.000000,1.000000,1.000000,1.000000], [0.748264,0.814647,0.711770,0.882497], [0.748264,0.271173,0.096328,0.161218], [0.101266,0.331211,0.711770,0.653770]])

mult1 = np.dot(m_normal, m_transposta)
print('primeira multiplicação:\n', mult1, '\n')

matrix_i = np.array([[0.1,0,0,0], [0,0.1,0,0], [0,0,0.1,0], [0,0,0,0.1]])

mult2 = np.add(mult1, matrix_i)
print('matriz antes de estar inversa:\n', mult2, '\n')

matrix_inverse = np.linalg.inv(mult2)
print('matriz inversa:\n', matrix_inverse, '\n')

targets = np.array([0.8,0.6,0.3,0.3])

txt = np.dot(m_transposta, targets)
print('transposta vezes targets:\n', txt, '\n')

res = np.dot(matrix_inverse, txt)
print('matriz inversa vezes a outra multiplicação:\n', res, '\n')

#b)
rmse = np.dot(m_normal, res)
print('matriz vezes w (rmse):\n',rmse, '\n')

primeira multiplicação:
 [[4.         3.163108   1.276983   1.798017  ]
 [3.157178   2.51318703 0.99164707 1.42916035]
 [1.276983   0.99221829 0.66870414 0.33955206]
 [1.798017   1.43338114 0.33955206 1.05398728]] 

matriz antes de estar inversa:
 [[4.1        3.163108   1.276983   1.798017  ]
 [3.157178   2.61318703 0.99164707 1.42916035]
 [1.276983   0.99221829 0.76870414 0.33955206]
 [1.798017   1.43338114 0.33955206 1.15398728]] 

matriz inversa:
 [[ 4.55625225 -3.78947542 -1.85929543 -1.8588796 ]
 [-3.78812887  6.00076704 -0.88808742 -1.268113  ]
 [-1.86424434 -0.88056356  4.33203722  2.72053034]
 [-1.84523569 -1.29017706  2.7253857   4.53750647]] 

transposta vezes targets:
 [1.5038174 1.4695034 1.4730494 1.5739946] 

matriz inversa vezes a outra multiplicação:
 [-4.38157608 -0.18270622  6.56593067  6.48582133] 

matriz vezes w (rmse):
 [ 8.48746969  6.96973362 -1.65000653  8.40944889] 

