In [11]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1,0.748264,0.748264,0.101266], [1,0.814647,0.271173,0.331211], [1,0.71770,0.096328,0.711770], [1,0.882497,0.161218,0.653770]])
matrix2 = np.array([[1,1,1,1], [0.748264,0.814647,0.711770,0.882497], [0.748264,0.271173,0.096328,0.161218], [0.101266,0.331211,0.711770,0.653770]])

# Multiply the matrices using numpy.dot
mult1 = np.dot(matrix2, matrix1)

print('matriz transposta vezes a normal:\n', mult1, '\n')

# Print the result
#print(mult1, '\n')

matrix_i = np.array([[0.1,0,0,0], [0,0.1,0,0], [0,0,0.1,0], [0,0,0,0.1]])

mult2 = np.add(mult1, matrix_i)

print('matriz antes de estar inversa:\n', mult2, '\n')

# Calculate the standard matrix inverse
matrix_inverse = np.linalg.inv(mult2)

print('matriz inversa:\n', matrix_inverse, '\n')

targets = np.array([0.8,0.6,0.3,0.3])

transp = np.dot(matrix2, targets)

print('transposta vezes targets:\n', transp, '\n')

res = np.dot(matrix_inverse,transp)

print('Matriz W:\n', res, '\n')


#b)

t_real = np.array([0.8, 0.6, 0.3, 0.3]) 

rmse = np.dot(matrix1, res)

print('matriz vezes w (rmse):\n',rmse, '\n')

erro_quadrado = (t_real - rmse)**2

# Cálculo do MSE (Mean Squared Error)
mse = np.mean(erro_quadrado)

# Cálculo do RMSE (Root Mean Square Error)
rmse_final = np.sqrt(mse)

print('RMSE:', rmse_final)

matriz transposta vezes a normal:
 [[4.         3.163108   1.276983   1.798017  ]
 [3.157178   2.51318703 0.99164707 1.42916035]
 [1.276983   0.99221829 0.66870414 0.33955206]
 [1.798017   1.43338114 0.33955206 1.05398728]] 

matriz antes de estar inversa:
 [[4.1        3.163108   1.276983   1.798017  ]
 [3.157178   2.61318703 0.99164707 1.42916035]
 [1.276983   0.99221829 0.76870414 0.33955206]
 [1.798017   1.43338114 0.33955206 1.15398728]] 

matriz inversa:
 [[ 4.55625225 -3.78947542 -1.85929543 -1.8588796 ]
 [-3.78812887  6.00076704 -0.88808742 -1.268113  ]
 [-1.86424434 -0.88056356  4.33203722  2.72053034]
 [-1.84523569 -1.29017706  2.7253857   4.53750647]] 

transposta vezes targets:
 [2.        1.5656795 0.8385788 0.6894014] 

Matriz W:
 [ 0.33872058  0.20005002  0.40112301 -0.29686118] 

matriz vezes w (rmse):
 [0.75849477 0.51214077 0.30963897 0.38585343] 

RMSE: 0.06501086671665518
