In [2]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1,0.748264,0.748264,0.101266], [1,0.814647,0.271173,0.331211], [1,0.71770,0.096328,0.711770], [1,0.882497,0.161218,0.653770]])
matrix2 = np.array([[1,1,1,1], [0.748264,0.814647,0.711770,0.882497], [0.748264,0.271173,0.096328,0.161218], [0.101266,0.331211,0.711770,0.653770]])

# Multiply the matrices using numpy.dot
mult1 = np.dot(matrix1, matrix2)

# Print the result
#print(mult1, '\n')

matrix_i = np.array([[0.1,0,0,0], [0,0.1,0,0], [0,0,0.1,0], [0,0,0,0.1]])

mult2 = np.add(mult1, matrix_i)

print('matriz antes de estar inversa:\n', mult2, '\n')

# Calculate the standard matrix inverse
matrix_inverse = np.linalg.inv(mult2)

print('matriz inversa:\n', matrix_inverse, '\n')

targets = np.array([0.8,0.6,0.3,0.3])

transp = np.dot(matrix1, targets)

print('transposta vezes targets:\n', transp, '\n')

res = np.dot(matrix_inverse, transp)

print('matriz inversa vezes a outra multiplicação:\n', res, '\n')


#b)
rmse = np.dot(matrix2, res)

print('matriz vezes w (rmse):\n',rmse, '\n')

matriz antes de estar inversa:
 [[2.23005283 1.84602043 1.67674874 1.84717903]
 [1.84602043 1.94688526 1.8417089  1.97917732]
 [1.68118595 1.84653976 2.12673295 2.11423178]
 [1.84717903 1.97917732 2.10899857 2.33220741]] 

matriz inversa:
 [[ 2.1468964  -2.33457816  0.50099777 -0.1733908 ]
 [-2.3340794   6.46520409 -1.4942947  -2.28326066]
 [ 0.50219069 -1.50283336  5.00299178 -3.65779929]
 [-0.17376862 -2.2784972  -3.65287448  5.81147069]] 

transposta vezes targets:
 [1.5038174 1.4695034 1.4730494 1.5739946] 

matriz inversa vezes a outra multiplicação:
 [0.26294792 0.19560033 0.15908207 0.15678328] 

matriz vezes w (rmse):
 [0.7744136  0.6076903  0.29039633 0.30714271] 

