In [1]:
import numpy as np

# Define two matrices
matrix1 = np.array([[0.748264,0.748264,0.101266], [0.814647,0.271173,0.331211], [0.71770,0.096328,0.711770], [0.882497,0.161218,0.653770]])
matrix2 = np.array([[0.748264,0.814647,0.711770,0.882497], [0.748264,0.271173,0.096328,0.161218], [0.101266,0.331211,0.711770,0.653770]])

# Multiply the matrices using numpy.dot
mult1 = np.dot(matrix2, matrix1)

# Print the result
#print(mult1, '\n')

matrix_i = np.array([[0.1,0,0], [0,0.1,0], [0,0,0.1]])

mult2 = np.add(mult1, matrix_i)

print('matriz antes de estar inversa:\n', mult2, '\n')

# Calculate the standard matrix inverse
matrix_inverse = np.linalg.inv(mult2)

print('matriz inversa:\n', matrix_inverse, '\n')

targets = np.array([0.8,0.6,0.3,0.3])

transp = np.dot(matrix2, targets)

print('transposta vezes targets:\n', transp, '\n')

res = np.dot(matrix_inverse, transp)

print('matriz inversa vezes a outra multiplicação:\n', res, '\n')


#b)

t_real = np.array([0.8, 0.6, 0.3, 0.3]) 

rmse = np.dot(matrix1, res)

print('matriz vezes w (rmse):\n',rmse, '\n')

erro_quadrado = (t_real - rmse)**2

# Cálculo do MSE (Mean Squared Error)
mse = np.mean(erro_quadrado)

# Cálculo do RMSE (Root Mean Square Error)
rmse_final = np.sqrt(mse)

print('RMSE:', rmse_final)


matriz antes de estar inversa:
 [[2.61318703 0.99164707 1.42916035]
 [0.99221829 0.76870414 0.33955206]
 [1.43338114 0.33955206 1.15398728]] 

matriz inversa:
 [[ 2.85014664 -2.43393044 -2.81361029]
 [-2.43107211  3.57128456  1.95994783]
 [-2.82487596  1.97239002  3.78467919]] 

transposta vezes targets:
 [1.5656795 0.8385788 0.6894014] 

matriz inversa vezes a outra multiplicação:
 [ 0.48166682  0.53971453 -0.1596828 ] 

matriz vezes w (rmse):
 [0.74809246 0.48585574 0.28402447 0.4076854 ] 

RMSE: 0.08302810921762396
